// Generated by gencpp from file pj_morse/greeting.msg
// DO NOT EDIT!


#ifndef PJ_MORSE_MESSAGE_GREETING_H
#define PJ_MORSE_MESSAGE_GREETING_H

#include <ros/service_traits.h>


#include <pj_morse/greetingRequest.h>
#include <pj_morse/greetingResponse.h>


namespace pj_morse
{

struct greeting
{

typedef greetingRequest Request;
typedef greetingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct greeting
} // namespace pj_morse


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pj_morse::greeting > {
  static const char* value()
  {
    return "116e2074a4605229af423317e5dff099";
  }

  static const char* value(const ::pj_morse::greeting&) { return value(); }
};

template<>
struct DataType< ::pj_morse::greeting > {
  static const char* value()
  {
    return "pj_morse/greeting";
  }

  static const char* value(const ::pj_morse::greeting&) { return value(); }
};


// service_traits::MD5Sum< ::pj_morse::greetingRequest> should match 
// service_traits::MD5Sum< ::pj_morse::greeting > 
template<>
struct MD5Sum< ::pj_morse::greetingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pj_morse::greeting >::value();
  }
  static const char* value(const ::pj_morse::greetingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pj_morse::greetingRequest> should match 
// service_traits::DataType< ::pj_morse::greeting > 
template<>
struct DataType< ::pj_morse::greetingRequest>
{
  static const char* value()
  {
    return DataType< ::pj_morse::greeting >::value();
  }
  static const char* value(const ::pj_morse::greetingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pj_morse::greetingResponse> should match 
// service_traits::MD5Sum< ::pj_morse::greeting > 
template<>
struct MD5Sum< ::pj_morse::greetingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pj_morse::greeting >::value();
  }
  static const char* value(const ::pj_morse::greetingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pj_morse::greetingResponse> should match 
// service_traits::DataType< ::pj_morse::greeting > 
template<>
struct DataType< ::pj_morse::greetingResponse>
{
  static const char* value()
  {
    return DataType< ::pj_morse::greeting >::value();
  }
  static const char* value(const ::pj_morse::greetingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PJ_MORSE_MESSAGE_GREETING_H
